kiite_me/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from km.views import homeView, loginView, signupView, logoutView, indexView,showView, newView, editView, deleteCommentView, editCommentView, deleteView, commentView, userListView, userMypageView, userMypageEditView, termsOfUseView, privacyPolicyView, contactFormView, userDeleteView, commentBackView, adminNotificationView, crop_image, UserCreate, signupAlumni, UserCreateDone, UserCreateComplete, reportPostView, reportCommentView, storyIndexView, story1View, story2View, storyShowView, newMentionedView, likeUnlikeCommentView, indexOthersView, UserNotificationView, switchNotifiStatusView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homeView, name='home'),

    path('signup/', signupView, name='altsignup'),
    path('accounts/login/', loginView, name='login'),
    path('accounts/logout/', logoutView, name='logout'),

    path('create/', UserCreate.as_view(), name='signup'),
    path('create_done_alumni/', signupAlumni, name='signupAlumni'),
    path('create_done/', UserCreateDone.as_view(), name='createDone'),
    path('create_complete/<token>/', UserCreateComplete.as_view(), name='createComplete'),

    path('posts/index/', indexView, name='postIndex'),
    path('posts/index/public_questions', indexOthersView, name='postIndexOthers'),
    path('posts/mention-new/<str:pk>', newMentionedView, name='postNewMentioned'),
    path('posts/new/', newView, name='postNew'),
    path('posts/show/<str:pk>', showView, name='postShow'),

    path('posts/edit/<str:pk>', editView, name='postEdit'),
    path('posts/comment/delete/<str:pk>', deleteCommentView, name='postCommentDelete'),
    path('posts/comment/edit/<str:pk>', editCommentView, name='postCommentEdit'),
    path('posts/comment/back/<str:pk>', commentBackView, name='postCommentBack'),
    path('posts/comment/likeUnlike/<str:pk>', likeUnlikeCommentView, name='likeUnlike'),
    path('posts/comment/report/<str:pk>', reportCommentView, name='reportComment'),
    path('posts/comment/<str:pk>', commentView, name='postComment'),
    path('posts/delete/<str:pk>', deleteView, name='postDelete'),
    path('posts/report/<str:pk>', reportPostView, name='reportPost'),

    path('user/list/<str:pk>', userListView, name="userList" ),
    path('user/mypage/', userMypageView, name="mypage" ),
    path('user/mypage/edit/', userMypageEditView, name="mypageEdit" ),
    path('user/delete_user_data', userDeleteView, name="userDelete" ),
    path('user/notification', UserNotificationView.as_view(), name="userNotification"),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset/password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset/password_reset_done.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset/password_reset_sent.html"), name="password_reset_complete"),

    path('policies/terms_of_use/', termsOfUseView, name="terms_of_use"),
    path('policies/privacy_policy/', privacyPolicyView, name="privacy_policy"),

    path('contact/form/', contactFormView, name="contactForm"),
    path('staff_only/', adminNotificationView, name="adminNotificationForm"),

    path('story/index/', storyIndexView, name="storyIndex"),
    path('story/take', story1View, name="story1"),
    path('story/toda', story2View, name="story2"),
    path('story/<str:pk>', storyShowView, name="storyShow"),

    path('<user_id>/edit/cropImage/', crop_image, name="crop_image" ),
    path('switch_notifi_status/', switchNotifiStatusView, name="switchNotifiStatus")
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

km/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from .managers import CustomUserManager


YEAR_CHOICES = []

for r in range(2016, (datetime.datetime.now().year+1)):
    YEAR_CHOICES.append((r,r))

def current_year():
    return datetime.date.today().year+1

def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)


# Job category refs : https://careergarden.jp/industry/
class AlumniJobParentCategory(models.Model):
    name = models.CharField(max_length=25)
    # date_created = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self):
        return self.name


class AlumniJobChildCategory(models.Model):
    name = models.CharField(max_length=25)
    parent = models.ForeignKey(AlumniJobParentCategory, verbose_name="親カテゴリー", on_delete=models.PROTECT)
    # date_created = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self):
        return self.name


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    name = models.CharField(max_length=30, null=True)
    real_name = models.CharField(max_length=40)
    profile_pic = models.ImageField(default='profile-icon-png-898.png', null=True, blank=True)
    introduction = models.TextField(max_length=200, default="まだプロフィールを記入していないようです、、、", null=True, blank=True,)
    id = models.BigAutoField(primary_key=True)

    UNDERGRADUATE = '在学生'
    ALUMNIUM = '卒業生'
    STUDENT_STATUS_CHOICES = (
        (UNDERGRADUATE, '在学生'),
        (ALUMNIUM, '卒業生')
    )
    student_status = models.CharField(max_length=3, choices=STUDENT_STATUS_CHOICES)
    #----for-undergraduate-------------
    entry_year = models.IntegerField(_('year'), validators=[MinValueValidator(2016), max_value_current_year], choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    #----for-alumni-------------
    industry = models.CharField(max_length=50, blank=True, null=True)
    job_type = models.CharField(max_length=50, blank=True, null=True)
    can_ask = models.BooleanField(default=False)
    job_category = models.ForeignKey(AlumniJobChildCategory, verbose_name="業界", blank=True, null=True, default=None, on_delete=models.PROTECT)
    #----for-new-user---------------
    key = models.CharField(max_length=255, unique=True, null=True)
    expiration_date = models.DateTimeField(blank=True, null=True)
    #--------------------------------
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(default=timezone.now, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    bronze = 5
    silver = 20
    gold = 50

    def show_rank(self):
        comment_count = Comment.objects.filter(user=self).count()
        if comment_count >= self.gold:
            return "gold"
        elif comment_count >= self.silver:
            return "silver"
        elif comment_count >= self.bronze:
            return "bronze"
        else:
            return None

    def remaining_comments_to_rankup(self):
        comment_count = Comment.objects.filter(user=self).count()
        current_rank = self.show_rank()
        if current_rank == None:
            return "あと{}回コメントで\nブロンズにランクアップ！".format(self.bronze-comment_count)
        elif current_rank == "bronze":
            return "あと{}回コメントで\nシルバーにランクアップ！".format(self.silver-comment_count)
        elif current_rank == "silver":
            return "あと{}回コメントで\nゴールドにランクアップ！".format(self.gold-comment_count)
        elif current_rank == "gold":
            return "おめでとうございます！\n最高ランクのゴールド達成です！"

    def __str__(self):
        return self.email


class Tag(models.Model):
    name = models.CharField(max_length=20, null=True)
    ordering_number = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['ordering_number']


class Post(models.Model):
    title = models.TextField(max_length=150, null=True)
    body = models.TextField(null=True)
    tag = models.ForeignKey(Tag, null=True,on_delete=models.SET_NULL, verbose_name='タグ')
    user = models.ForeignKey(CustomUser,null=True, on_delete= models.SET_NULL)
    mentioned_user = models.ForeignKey(CustomUser, null=True, blank=True, on_delete= models.SET_NULL, related_name='mentioned_user')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    is_public = models.BooleanField()
    user_is_anonymous = models.BooleanField()
    requested_industry = models.ForeignKey(AlumniJobChildCategory, on_delete=models.SET_NULL, null=True, blank=True)
    requested_parent_industry = models.ForeignKey(AlumniJobParentCategory, on_delete=models.SET_NULL, null=True, blank=True)

    def get_comments_count(self):
        return Comment.objects.filter(post=self).count()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(CustomUser, null=True, on_delete= models.SET_NULL)
    body = models.TextField()
    like_user_list = models.ManyToManyField(CustomUser, blank=True, related_name="like_user_list")
    is_reply_to = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, default=None)
    date_added = models.DateTimeField(auto_now_add=True)

    def count_like(self):
        return self.like_user_list.count()

    def __str__(self):
        return '%s - %s - %s' % (self.post.title, self.user, self.body[:20])
        #this is how it is written in python2 mainly,
        #you'd better write return self.post.title + self.user in python3

    class Meta:
        ordering = ['date_added']


class Article(models.Model):
    title            = models.TextField()
    industry         = models.CharField(max_length=20, default=None)
    body             = models.TextField(default=None)
    user             = models.ForeignKey(CustomUser, null=True, on_delete= models.SET_NULL)
    interviewee_name = models.CharField(max_length=40, null=True, blank=True)
    interviewee_pic  = models.ImageField(null=True, blank=True)
    date_added       = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title

class OfferedJobJoinTable(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    offered_job_parent_category = models.ForeignKey(AlumniJobParentCategory, default=None, on_delete=models.PROTECT)
    offered_job_child_category = models.ForeignKey(AlumniJobChildCategory, default=None, on_delete=models.CASCADE)
    
    def __str__(self):
        return '%s - %s (%s)' % (self.user.name, self.offered_job_child_category, self.offered_job_parent_category)

class UserNotification(models.Model):
    title        = models.CharField(max_length=200)
    body         = models.TextField()
    date_added   = models.DateTimeField(auto_now_add=True)
    user         = models.ForeignKey(CustomUser, blank=True, on_delete=models.CASCADE)
    is_seen      = models.BooleanField(default=False)
    related_post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        return "{} -> {}".format(self.title, self.user)

km/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django import  forms
from .models import *

User = get_user_model()

# maybe not needed anymore
class StudentForm(ModelForm):
    job_parent_category = forms.ModelChoiceField(
        label='親カテゴリー',
        queryset=AlumniJobParentCategory.objects,
        required=False
        )

    class Meta: 
        model = CustomUser
        fields = '__all__'
        exclude = ['user']

class CustomUserCreationForm(UserCreationForm):
    job_parent_category = forms.ModelChoiceField(
        label='親カテゴリー',
        queryset=AlumniJobParentCategory.objects,
        required=False
        )

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('real_name','name','email','entry_year','industry', 'job_type','job_parent_category', 'job_category','student_status')

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

class CustomUserChangeForm(UserChangeForm):
    job_parent_category = forms.ModelChoiceField(
        label='親カテゴリー',
        queryset=AlumniJobParentCategory.objects,
        required=False
        )
        
    class Meta:
        model = CustomUser
        fields = ('real_name','name','email','entry_year','profile_pic','industry', 'job_type','job_parent_category', 'job_category', 'introduction','can_ask')

# class OfferedJobForm(UserChangeForm):
#     job_parent_category = forms.ModelChoiceField(
#         label='親カテゴリー',
#         queryset=AlumniJobParentCategory.objects,
#         required=False
#         )
        
#     class Meta:
#         model = OfferedJobJoinTable
#         fields = ('job_parent_category', 'offered_job_category',)

class PostForm(ModelForm):
    job_parent_category = forms.ModelChoiceField(
        label='親カテゴリー',
        queryset=AlumniJobParentCategory.objects,
        required=False
        )

    class Meta:
        model = Post
        fields = ['title','tag', 'body','is_public', 'user_is_anonymous', 'job_parent_category', 'requested_industry']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body',]

class ContactForm(forms.Form):
    toEmail = forms.EmailField()
    title = forms.fields.ChoiceField(
        choices = (
            ('お問い合わせ内容：お問い合わせ', 'お問い合わせ'),
            ('お問い合わせ内容：通報', '通報'),
            ('お問い合わせ内容：改善の要望', '改善の要望'),
        ),
        required=True,
        widget=forms.widgets.Select
    )
    body = forms.CharField(widget=forms.Textarea)

    def __str__(self):
        return self.toEmail
        
class adminNotificationForm(forms.Form):
    toGroup= forms.fields.ChoiceField(
        choices = (
            ('ユーザーの皆様', '全てのユーザー'),
            ('ユーザー（在学生）の皆様', '在学生'),
            ('ユーザー（卒業生）の皆様', '卒業生'),
            ('スタッフの皆様', 'スタッフへの連絡'),
        ),
        required=True,
        widget=forms.widgets.Select
    )
    title = forms.CharField()
    body = forms.CharField(widget=forms.Textarea)

    def __str__(self):
        return self.title

OfferedJobFormset = forms.inlineformset_factory(
        parent_model = CustomUser,
        model = OfferedJobJoinTable,
        fields = ('offered_job_child_category', 'offered_job_parent_category'),
        extra = 3,
        max_num = 3,
        can_delete=True,
    )

templates/posts/delete.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="main posts-show">
    <div class="container">
      <div class="posts-show-item">

        <p>本当にこの質問を削除しますか？</p>

        <p>{{ post.title }}</p>
        <p>{{ post.body | linebreaksbr }}</p>

        <form action="{% url 'postDelete' post.id %}" method="POST">{% csrf_token %}
          
          <input type="submit" value="はい" name="Confirm">
          <a href="{% url 'postShow' post.id %}" class="choice-no">いいえ</a>
        </form>

        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/posts/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="main posts-index">
    <div class="container">
      {% if request.user.student_status == '在学生' %}
      <div class="form-heading" style="margin-top:0px">Your Questions</div>
      {% else %}
      <div class="form-heading" style="margin-top:0px">Questions</div>
      {% endif %}

      {% if request.user.student_status == '卒業生'%}
      <form method="GET">
        {{ post_filter.form.title.label_tag }}
        {{ post_filter.form.title }}
        <div class="kensakutag">
        {{ post_filter.form.tag.label_tag }}
        {{ post_filter.form.tag }}
        </div>
        <button id="kensaku" class="btn btn-primary" type="submit">検索</button>
      </form>
      <div class="hitnum">
        <p>検索結果：{{ post_list|length }} 件 ( {{from_num}}~{{to_num}}件表示 )</p>
      </div>
      {% else %}
        <div class="row" style="margin-bottom: 12px;">
          <div class="col-xs-6" style="padding-right: 0px;">
            <a href="#" class="btn btn-default btn-block active" role="button">自分の質問
            </a>
          </div>
          <div class="col-xs-6" style="padding-left: 0px;">
            <a href="{% url 'postIndexOthers' %}" class="btn btn-default btn-block" role="button">みんなの質問
            </a>
          </div>
        </div>
        {% comment %}
        <!-- 2022/4/1サービス終了に伴い質問機能を蓋締め -->
        {% if not posts %}
          <a href="{% url 'postNew' %}">
            <h2 style="text-align:center; text-decoration: none; margin-top:13%; color:rgb(133, 133, 133);">Let's ask whatever question you've got!</h2>
          </a>
          <div class="button-section">
            <a href="{% url 'postNew' %}" class="btn-text-3d" style="text-decoration: none; color:#fff;">質問を作成！</a>
          </div>
        {% endif %}
        {% endcomment %}
      {% endif %}

      {% for post in posts %}
        <div class="posts-index-item">
          {% if post.mentioned_user %}
            {% if request.user == post.mentioned_user %}
              <a href="{% url 'userList' post.mentioned_user.id %}" class="text-danger">@ {{ post.mentioned_user.name }} さん</a><br>
              {% else %}
              <a href="{% url 'userList' post.mentioned_user.id %}" style="font-size:14px;">@ {{ post.mentioned_user.name }} さん</a><br>
            {% endif %}
          {% endif %}
          {% if post.requested_parent_industry %}
            {% if request.user.job_category == post.requested_parent_industry %}
              <b class="fs-14 text-danger"># {{ post.requested_parent_industry }} 業界</b><br>
            {% else %}
              <b class="fs-14"># {{ post.requested_parent_industry }} 業界</b><br>
            {% endif %}
          {% elif post.requested_industry %}
            {% if request.user.job_category.parent == post.requested_industry %}
              <b class="fs-14 text-danger"># {{ post.requested_industry }} 業界</b><br>
            {% else %}
              <b class="fs-14"># {{ post.requested_industry }} 業界</b><br>
            {% endif %}
          {% endif %}
          <a href="{% url 'postShow' post.id %}"><b>{{ post.title|truncatechars:45 }}</b></a><br>
          <p><svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-chat-dots" viewBox="0 0 16 16">
            <path d="M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
            <path d="M2.165 15.803l.02-.004c1.83-.363 2.948-.842 3.468-1.105A9.06 9.06 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.437 10.437 0 0 1-.524 2.318l-.003.011a10.722 10.722 0 0 1-.244.637c-.079.186.074.394.273.362a21.673 21.673 0 0 0 .693-.125zm.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6c0 3.193-3.004 6-7 6a8.06 8.06 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a10.97 10.97 0 0 0 .398-2z"/>
          </svg>  {{ post.get_comments_count }}</p>
          <p id="post_tag_index">#{{ post.tag  }}</p>
        </div>
      {% endfor %}
    </div>
</div>

<div class="pager">
  {% if posts.has_other_pages %}
  <ul class="pagination">
    {% if posts.has_previous %}
      <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
      {% if posts.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
  {% endif %}
</div>

{% comment %}
<!-- 2022/4/1サービス終了に伴い質問機能を蓋締め -->
{% if posts %}
  {% if request.user.student_status == '在学生' %}
    <div class="newpostlink"><a href="{% url 'postNew' %}" class="btn-text-3d" style="text-decoration: none; color:#fff; width:74px; height:74px; line-height:74px; letter-spacing: 1px; font-size:13px;">質問作成</a></div>
  {% endif %}
{% endif %}
{% endcomment %}
{% endblock %}

templates/posts/job_category_search.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}


<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script>
  const parentCategoryElement = $('#id_job_parent_category')
  const categoryElement = $('#id_job_category')
  const categories = {
    {% for parent in parentcategory_list %}
      '{{ parent.pk }}' : [
        {% for category in parent.alumnijobchildcategory_set.all %}
          {
            'pk': '{{ category.pk }}',
            'name': '{{ category.name }}'
          },
        {% endfor %}
      ],
    {% endfor %}
  };

  const changeCategory = (select) => {
    categoryElement.children().remove();
    categoryElement.removeClass('hide');

    const parentId = parentCategoryElement.val();
    const categoryList = categories[parentId];

    // 子カテゴリの選択肢を作成、追加。
    for (const category of categoryList) {
      const option = $('<option>');
      option.val(category['pk']);
      option.text(category['name']);
      categoryElement.append(option);
    }

    // 指定があればそのカテゴリを選択する
    if (select !== undefined) {
      categoryElement.val(select);
    }
  };
  
  $('#id_job_parent_category').on('change', () =>{
      changeCategory();
    });

  // 入力値に不備があってリロードがかかった時に、ページ表示時点で小カテゴリが絞り込まれるようにする
  if (parentCategoryElement.val()) {
    const selectCategory = categoryElement.val();
    changeCategory(selectCategory);
  }
</script>
{% endblock %}

templates/posts/new.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="main posts-show">
    <div class="container">
      <div class="posts-show-item">
        {% if mentioned_user %}
        <p style="font-size:16px;">送信先 :
          <a href="{% url 'userList' mentioned_user.id %}"><img src="{{ mentioned_user.profile_pic.url }}" alt="profile pic" style="width:34px; height:34px; border-radius: 45%;"> {{ mentioned_user.name }}</a> さん
        </p>
        {% endif %}

        <form action="" method="POST">
          {% csrf_token %}
          <p style="margin-top:0px;">質問タイトル <span style="color:rgb(214, 16, 16);">*</span></p>
          {{ form.title|add_class:"newpost-title" }}
          <p>関連タグ<span style="color:rgb(214, 16, 16);">*</span></p>
          {{ form.tag|add_class:"form-control" }}

          <div class="job_form">
            <p style="display: inline-block;">業界指定</p>
            <button type="button" class="btn btn-danger job-form-reset-btn hide">リセット</button>

            <p class="fs-13" style="margin:0;">大分類</p>
            {{ form.job_parent_category | add_class:"form-control parent-form" }}
            <br>
            <p class="fs-13" style="margin:0;">小分類</p>
            {{ form.requested_industry | add_class:"form-control child-form" | attr:"disabled" }}
            <p class="fs-14" style="margin:0;">　※ 回答可能な卒業生が登録されている業界のみ選択可能となっています。</p>
            <p class="fs-14" style="margin:0;">　※ 細かく業界を指定したい場合は小分類まで選択してください。</p>
          </div>

          <p>質問内容 <span style="color:rgb(214, 16, 16);">*</span></p>
          {{ form.body|add_class:"newpost-body form-control" }}
          <div class="checkbox">
            <label>
              {{ form.is_public }}
              他の在学生にも質問を公開する
            </label>
          </div>
          <div class="checkbox">
            <label>
              {{ form.user_is_anonymous }}
              ユーザー情報を隠して質問を投稿する
            </label>
          </div>
          <input type="submit" class="btn btn-primary" style="height:auto; width:auto; border-radius:5px; border:none;" name="Submit" value="質問を投稿">
        </form>
        {{form.errors}}
        </div>
      </div>
      <div class="emptybox"></div>
    </div>
  </div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script>
  // 業界選択時の処理
  const categories = {
    {% for parent in parent_category_list %}
      '{{ parent.pk }}' : [
        {% for category in parent.alumnijobchildcategory_set.all %}
          {
            'pk': '{{ category.pk }}',
            'name': '{{ category.name }}'
          },
        {% endfor %}
      ],
    {% endfor %}
  };

  const availableParentIndustryList = {{ available_parent_industry_list }}
  $('.job_form select.parent-form option').each( function( i ) {
    if (jQuery.inArray(parseInt($(this).val()), availableParentIndustryList) == -1 ) {
      $(this).prop('disabled', true);
    }
  });

  function disbaleUnavailableIndustries() {
    const availableChildIndustryList = {{ available_child_industry_list }}
    let index = 0;
    $('.job_form select.child-form option').each( function( i ) {
      if (index > 0) {
        if (jQuery.inArray(parseInt($(this).val()), availableChildIndustryList) == -1 ) {
          $(this).prop('disabled', true);
        }
      }
      index++;
    });
  }

  $('.job_form select.parent-form').on('change', function (){
    const childJobCategoryElem = $(this).siblings('select');
    const parentJobCategoryElem = $(this);

    childJobCategoryElem.children().remove();
    childJobCategoryElem.removeAttr('disabled');

    const parentId = parentJobCategoryElem.val();
    const categoryList = categories[parentId];

    // 子カテゴリの選択肢を作成、追加。
    childJobCategoryElem.append($('<option value="">---------</option>'));
    for (const category of categoryList) {
      const option = $('<option>');
      option.val(category['pk']);
      option.text(category['name']);
      childJobCategoryElem.append(option);
    }

    $(this).siblings('.job-form-reset-btn').removeClass('hide');
    disbaleUnavailableIndustries()
  });

  // reset job select form
  $(document).on('click', '.job-form-reset-btn', function() {
    $(this).siblings('select.parent-form').find('option:eq(0)').prop('selected', true);
    $(this).siblings('select.child-form').find('option:eq(0)').prop('selected', true);
    $(this).siblings('select.child-form').prop('disabled', true);
    $(this).addClass('hide');
  });

</script>
{% endblock %}