kiite_me/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from km.views import homeView, loginView, signupView, logoutView, indexView,showView, newView, editView, deleteCommentView, editCommentView, deleteView, commentView, userListView, userMypageView, userMypageEditView, termsOfUseView, privacyPolicyView, contactFormView, userDeleteView, commentBackView, adminNotificationView, crop_image, UserCreate, signupAlumni, UserCreateDone, UserCreateComplete, reportPostView, reportCommentView, storyIndexView, story1View, story2View, storyShowView, newMentionedView, likeUnlikeCommentView, indexOthersView, UserNotificationView, switchNotifiStatusView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homeView, name='home'),

    path('signup/', signupView, name='altsignup'),
    path('accounts/login/', loginView, name='login'),
    path('accounts/logout/', logoutView, name='logout'),

    path('create/', UserCreate.as_view(), name='signup'),
    path('create_done_alumni/', signupAlumni, name='signupAlumni'),
    path('create_done/', UserCreateDone.as_view(), name='createDone'),
    path('create_complete/<token>/', UserCreateComplete.as_view(), name='createComplete'),

    path('posts/index/', indexView, name='postIndex'),
    path('posts/index/public_questions', indexOthersView, name='postIndexOthers'),
    path('posts/mention-new/<str:pk>', newMentionedView, name='postNewMentioned'),
    path('posts/new/', newView, name='postNew'),
    path('posts/show/<str:pk>', showView, name='postShow'),

    path('posts/edit/<str:pk>', editView, name='postEdit'),
    path('posts/comment/delete/<str:pk>', deleteCommentView, name='postCommentDelete'),
    path('posts/comment/edit/<str:pk>', editCommentView, name='postCommentEdit'),
    path('posts/comment/back/<str:pk>', commentBackView, name='postCommentBack'),
    path('posts/comment/likeUnlike/<str:pk>', likeUnlikeCommentView, name='likeUnlike'),
    path('posts/comment/report/<str:pk>', reportCommentView, name='reportComment'),
    path('posts/comment/<str:pk>', commentView, name='postComment'),
    path('posts/delete/<str:pk>', deleteView, name='postDelete'),
    path('posts/report/<str:pk>', reportPostView, name='reportPost'),

    path('user/list/<str:pk>', userListView, name="userList" ),
    path('user/mypage/', userMypageView, name="mypage" ),
    path('user/mypage/edit/', userMypageEditView, name="mypageEdit" ),
    path('user/delete_user_data', userDeleteView, name="userDelete" ),
    path('user/notification', UserNotificationView.as_view(), name="userNotification"),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset/password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset/password_reset_done.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset/password_reset_sent.html"), name="password_reset_complete"),

    path('policies/terms_of_use/', termsOfUseView, name="terms_of_use"),
    path('policies/privacy_policy/', privacyPolicyView, name="privacy_policy"),

    path('contact/form/', contactFormView, name="contactForm"),
    path('staff_only/', adminNotificationView, name="adminNotificationForm"),

    path('story/index/', storyIndexView, name="storyIndex"),
    path('story/take', story1View, name="story1"),
    path('story/toda', story2View, name="story2"),
    path('story/<str:pk>', storyShowView, name="storyShow"),

    path('<user_id>/edit/cropImage/', crop_image, name="crop_image" ),
    path('switch_notifi_status/', switchNotifiStatusView, name="switchNotifiStatus")
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

km/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django import  forms
from .models import *

User = get_user_model()

# maybe not needed anymore
class StudentForm(ModelForm):
    job_parent_category = forms.ModelChoiceField(
        label='親カテゴリー',
        queryset=AlumniJobParentCategory.objects,
        required=False
        )

    class Meta: 
        model = CustomUser
        fields = '__all__'
        exclude = ['user']

class CustomUserCreationForm(UserCreationForm):
    job_parent_category = forms.ModelChoiceField(
        label='親カテゴリー',
        queryset=AlumniJobParentCategory.objects,
        required=False
        )

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('real_name','name','email','entry_year','industry', 'job_type','job_parent_category', 'job_category','student_status')

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

class CustomUserChangeForm(UserChangeForm):
    job_parent_category = forms.ModelChoiceField(
        label='親カテゴリー',
        queryset=AlumniJobParentCategory.objects,
        required=False
        )
        
    class Meta:
        model = CustomUser
        fields = ('real_name','name','email','entry_year','profile_pic','industry', 'job_type','job_parent_category', 'job_category', 'introduction','can_ask')

# class OfferedJobForm(UserChangeForm):
#     job_parent_category = forms.ModelChoiceField(
#         label='親カテゴリー',
#         queryset=AlumniJobParentCategory.objects,
#         required=False
#         )
        
#     class Meta:
#         model = OfferedJobJoinTable
#         fields = ('job_parent_category', 'offered_job_category',)

class PostForm(ModelForm):
    job_parent_category = forms.ModelChoiceField(
        label='親カテゴリー',
        queryset=AlumniJobParentCategory.objects,
        required=False
        )

    class Meta:
        model = Post
        fields = ['title','tag', 'body','is_public', 'user_is_anonymous', 'job_parent_category', 'requested_industry']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body',]

class ContactForm(forms.Form):
    toEmail = forms.EmailField()
    title = forms.fields.ChoiceField(
        choices = (
            ('お問い合わせ内容：お問い合わせ', 'お問い合わせ'),
            ('お問い合わせ内容：通報', '通報'),
            ('お問い合わせ内容：改善の要望', '改善の要望'),
        ),
        required=True,
        widget=forms.widgets.Select
    )
    body = forms.CharField(widget=forms.Textarea)

    def __str__(self):
        return self.toEmail
        
class adminNotificationForm(forms.Form):
    toGroup= forms.fields.ChoiceField(
        choices = (
            ('ユーザーの皆様', '全てのユーザー'),
            ('ユーザー（在学生）の皆様', '在学生'),
            ('ユーザー（卒業生）の皆様', '卒業生'),
            ('スタッフの皆様', 'スタッフへの連絡'),
        ),
        required=True,
        widget=forms.widgets.Select
    )
    title = forms.CharField()
    body = forms.CharField(widget=forms.Textarea)

    def __str__(self):
        return self.title

OfferedJobFormset = forms.inlineformset_factory(
        parent_model = CustomUser,
        model = OfferedJobJoinTable,
        fields = ('offered_job_child_category', 'offered_job_parent_category'),
        extra = 3,
        max_num = 3,
        can_delete=True,
    )

templates/contact/admin_notification.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    <div class="main users-new">
        <div class="container">
        <div class="form-heading">Notification Page</div>
        <div class="form users-form">
            <div class="form-body">
    
            <form method="POST" action="">
                {% csrf_token %}
                
                <p>送付先グループ</p>
                {{ form.toGroup }}

                <p>件名（【kiite-me】は自動で追加されます。）</p>
                {{ form.title }}

                <p>内容</p>
                {{ form.body }}

                <input type="submit" name="ContactForm" value="送信" id="show_spinner">
            </form>
            {{ form.errors }}
            </div>
        </div>
        </div>
    </div>
<!-- spinner section -->
<div class="spinner-div" id="id_spinner">
    <div class="loader" id="loader-1"></div>
</div>
<script type="text/javascript">
    var show_spinner_event = document.getElementById("show_spinner")
    show_spinner_event.addEventListener("click", showSpinner);
    function showSpinner(){
        document.getElementById("id_spinner").style.display = "block";
    }
</script>
{% endblock %}

templates/contact/contact_form.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    <div class="main users-new">
        <div class="container">
        <div class="form-heading">Contact us</div>
        <div class="form users-form">
            <div class="form-body">
    
            <form method="POST" action="">
                {% csrf_token %}
                
                <p>連絡先メールアドレス</p>
                {% if request.user.is_authenticated %}
                    <input type="email" name="toEmail" required id="id_toEmail" value="{{ request.user.email }}">
                {% else %}
                    {{ form.toEmail }}
                {% endif %}

                <p>お問い合わせ内容</p>
                {{ form.title }}

                <p>内容</p>
                {{ form.body }}

                <input type="submit" name="ContactForm" value="送信">
            </form>
            {{ form.errors }}
            </div>
        </div>
        </div>
    </div>

{% endblock %}

templates/contact/contact_sent.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}


  　<div class="main mypage-show">
    <div class="container">
        <div class="mypage-show-item">
            <h2>お問い合わせが送信されました。</h2>
            
            <p>運営事務局からの返信をお待ちください。<br>{{recepient}}にメールを送信しています。併せてご確認ください。</p>
        </div>
    </div>
</div>
  
{% endblock %}

templates/contact/report.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="main posts-show">
    <div class="container">
      <div class="posts-show-item">
        <div class="asker">
          {% if post_or_comment.user.name %}
          <h4><a class="userLink" href="{% url 'userList' post_or_comment.user.id %}">{{ post_or_comment.user.name }}</a></h4> <!-- ####### -->
          {% else %}
          <h4>退会済みユーザー</h4>
          {% endif %}
        </div>
        <p><b>{{ post_or_comment.title }}</b><br>{{ post_or_comment.body | linebreaksbr }}</p>
      </div>

      <p id="commenthere">通報内容*</p>
      <form action="" method="POST">
          {% csrf_token %}
          {{ form.body }}
          <input type="submit" class="btn btn-warning" value="送信">
      </form>

    </div>
  </div>
  <div class="emptybox"></div>
{% endblock %}

templates/contact/sent_admin_notification.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}


  　<div class="main mypage-show">
    <div class="container">
        <div class="mypage-show-item">
            <h2>お知らせが送信されました。</h2>
            
            <p>Gメールを確認してメールが問題なく送信されているか確認をお願いします。</p>
        </div>
    </div>
</div>
  
{% endblock %}