kiite_me/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from km.views import homeView, loginView, signupView, logoutView, indexView,showView, newView, editView, deleteCommentView, editCommentView, deleteView, commentView, userListView, userMypageView, userMypageEditView, termsOfUseView, privacyPolicyView, contactFormView, userDeleteView, commentBackView, adminNotificationView, crop_image, UserCreate, signupAlumni, UserCreateDone, UserCreateComplete, reportPostView, reportCommentView, storyIndexView, story1View, story2View, storyShowView, newMentionedView, likeUnlikeCommentView, indexOthersView, UserNotificationView, switchNotifiStatusView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homeView, name='home'),

    path('signup/', signupView, name='altsignup'),
    path('accounts/login/', loginView, name='login'),
    path('accounts/logout/', logoutView, name='logout'),

    path('create/', UserCreate.as_view(), name='signup'),
    path('create_done_alumni/', signupAlumni, name='signupAlumni'),
    path('create_done/', UserCreateDone.as_view(), name='createDone'),
    path('create_complete/<token>/', UserCreateComplete.as_view(), name='createComplete'),

    path('posts/index/', indexView, name='postIndex'),
    path('posts/index/public_questions', indexOthersView, name='postIndexOthers'),
    path('posts/mention-new/<str:pk>', newMentionedView, name='postNewMentioned'),
    path('posts/new/', newView, name='postNew'),
    path('posts/show/<str:pk>', showView, name='postShow'),

    path('posts/edit/<str:pk>', editView, name='postEdit'),
    path('posts/comment/delete/<str:pk>', deleteCommentView, name='postCommentDelete'),
    path('posts/comment/edit/<str:pk>', editCommentView, name='postCommentEdit'),
    path('posts/comment/back/<str:pk>', commentBackView, name='postCommentBack'),
    path('posts/comment/likeUnlike/<str:pk>', likeUnlikeCommentView, name='likeUnlike'),
    path('posts/comment/report/<str:pk>', reportCommentView, name='reportComment'),
    path('posts/comment/<str:pk>', commentView, name='postComment'),
    path('posts/delete/<str:pk>', deleteView, name='postDelete'),
    path('posts/report/<str:pk>', reportPostView, name='reportPost'),

    path('user/list/<str:pk>', userListView, name="userList" ),
    path('user/mypage/', userMypageView, name="mypage" ),
    path('user/mypage/edit/', userMypageEditView, name="mypageEdit" ),
    path('user/delete_user_data', userDeleteView, name="userDelete" ),
    path('user/notification', UserNotificationView.as_view(), name="userNotification"),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset/password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset/password_reset_done.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset/password_reset_sent.html"), name="password_reset_complete"),

    path('policies/terms_of_use/', termsOfUseView, name="terms_of_use"),
    path('policies/privacy_policy/', privacyPolicyView, name="privacy_policy"),

    path('contact/form/', contactFormView, name="contactForm"),
    path('staff_only/', adminNotificationView, name="adminNotificationForm"),

    path('story/index/', storyIndexView, name="storyIndex"),
    path('story/take', story1View, name="story1"),
    path('story/toda', story2View, name="story2"),
    path('story/<str:pk>', storyShowView, name="storyShow"),

    path('<user_id>/edit/cropImage/', crop_image, name="crop_image" ),
    path('switch_notifi_status/', switchNotifiStatusView, name="switchNotifiStatus")
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

km/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from .managers import CustomUserManager


YEAR_CHOICES = []

for r in range(2016, (datetime.datetime.now().year+1)):
    YEAR_CHOICES.append((r,r))

def current_year():
    return datetime.date.today().year+1

def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)


# Job category refs : https://careergarden.jp/industry/
class AlumniJobParentCategory(models.Model):
    name = models.CharField(max_length=25)
    # date_created = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self):
        return self.name


class AlumniJobChildCategory(models.Model):
    name = models.CharField(max_length=25)
    parent = models.ForeignKey(AlumniJobParentCategory, verbose_name="親カテゴリー", on_delete=models.PROTECT)
    # date_created = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self):
        return self.name


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    name = models.CharField(max_length=30, null=True)
    real_name = models.CharField(max_length=40)
    profile_pic = models.ImageField(default='profile-icon-png-898.png', null=True, blank=True)
    introduction = models.TextField(max_length=200, default="まだプロフィールを記入していないようです、、、", null=True, blank=True,)
    id = models.BigAutoField(primary_key=True)

    UNDERGRADUATE = '在学生'
    ALUMNIUM = '卒業生'
    STUDENT_STATUS_CHOICES = (
        (UNDERGRADUATE, '在学生'),
        (ALUMNIUM, '卒業生')
    )
    student_status = models.CharField(max_length=3, choices=STUDENT_STATUS_CHOICES)
    #----for-undergraduate-------------
    entry_year = models.IntegerField(_('year'), validators=[MinValueValidator(2016), max_value_current_year], choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    #----for-alumni-------------
    industry = models.CharField(max_length=50, blank=True, null=True)
    job_type = models.CharField(max_length=50, blank=True, null=True)
    can_ask = models.BooleanField(default=False)
    job_category = models.ForeignKey(AlumniJobChildCategory, verbose_name="業界", blank=True, null=True, default=None, on_delete=models.PROTECT)
    #----for-new-user---------------
    key = models.CharField(max_length=255, unique=True, null=True)
    expiration_date = models.DateTimeField(blank=True, null=True)
    #--------------------------------
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(default=timezone.now, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    bronze = 5
    silver = 20
    gold = 50

    def show_rank(self):
        comment_count = Comment.objects.filter(user=self).count()
        if comment_count >= self.gold:
            return "gold"
        elif comment_count >= self.silver:
            return "silver"
        elif comment_count >= self.bronze:
            return "bronze"
        else:
            return None

    def remaining_comments_to_rankup(self):
        comment_count = Comment.objects.filter(user=self).count()
        current_rank = self.show_rank()
        if current_rank == None:
            return "あと{}回コメントで\nブロンズにランクアップ！".format(self.bronze-comment_count)
        elif current_rank == "bronze":
            return "あと{}回コメントで\nシルバーにランクアップ！".format(self.silver-comment_count)
        elif current_rank == "silver":
            return "あと{}回コメントで\nゴールドにランクアップ！".format(self.gold-comment_count)
        elif current_rank == "gold":
            return "おめでとうございます！\n最高ランクのゴールド達成です！"

    def __str__(self):
        return self.email


class Tag(models.Model):
    name = models.CharField(max_length=20, null=True)
    ordering_number = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['ordering_number']


class Post(models.Model):
    title = models.TextField(max_length=150, null=True)
    body = models.TextField(null=True)
    tag = models.ForeignKey(Tag, null=True,on_delete=models.SET_NULL, verbose_name='タグ')
    user = models.ForeignKey(CustomUser,null=True, on_delete= models.SET_NULL)
    mentioned_user = models.ForeignKey(CustomUser, null=True, blank=True, on_delete= models.SET_NULL, related_name='mentioned_user')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    is_public = models.BooleanField()
    user_is_anonymous = models.BooleanField()
    requested_industry = models.ForeignKey(AlumniJobChildCategory, on_delete=models.SET_NULL, null=True, blank=True)
    requested_parent_industry = models.ForeignKey(AlumniJobParentCategory, on_delete=models.SET_NULL, null=True, blank=True)

    def get_comments_count(self):
        return Comment.objects.filter(post=self).count()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(CustomUser, null=True, on_delete= models.SET_NULL)
    body = models.TextField()
    like_user_list = models.ManyToManyField(CustomUser, blank=True, related_name="like_user_list")
    is_reply_to = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, default=None)
    date_added = models.DateTimeField(auto_now_add=True)

    def count_like(self):
        return self.like_user_list.count()

    def __str__(self):
        return '%s - %s - %s' % (self.post.title, self.user, self.body[:20])
        #this is how it is written in python2 mainly,
        #you'd better write return self.post.title + self.user in python3

    class Meta:
        ordering = ['date_added']


class Article(models.Model):
    title            = models.TextField()
    industry         = models.CharField(max_length=20, default=None)
    body             = models.TextField(default=None)
    user             = models.ForeignKey(CustomUser, null=True, on_delete= models.SET_NULL)
    interviewee_name = models.CharField(max_length=40, null=True, blank=True)
    interviewee_pic  = models.ImageField(null=True, blank=True)
    date_added       = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title

class OfferedJobJoinTable(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    offered_job_parent_category = models.ForeignKey(AlumniJobParentCategory, default=None, on_delete=models.PROTECT)
    offered_job_child_category = models.ForeignKey(AlumniJobChildCategory, default=None, on_delete=models.CASCADE)
    
    def __str__(self):
        return '%s - %s (%s)' % (self.user.name, self.offered_job_child_category, self.offered_job_parent_category)

class UserNotification(models.Model):
    title        = models.CharField(max_length=200)
    body         = models.TextField()
    date_added   = models.DateTimeField(auto_now_add=True)
    user         = models.ForeignKey(CustomUser, blank=True, on_delete=models.CASCADE)
    is_seen      = models.BooleanField(default=False)
    related_post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        return "{} -> {}".format(self.title, self.user)

templates/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<!-- home section -->
<section id="home">
	
	<img id="homepic"
	{% if random_num == 0 %}   src="{% static 'images/home-pics/tedtim.jpg' %}"
	{% elif random_num == 1 %} src="{% static 'images/home-pics/CommunicationRoom.jpg' %}"
	{% elif random_num == 2 %} src="{% static 'images/home-pics/campus1.JPG' %}"
	{% elif random_num == 3 %} src="{% static 'images/home-pics/campus2.JPG' %}"
	{% elif random_num == 4 %} src="{% static 'images/home-pics/campus3.JPG' %}"
	{% elif random_num == 5 %} src="{% static 'images/home-pics/room1.JPG' %}"
	{% elif random_num == 6 %} src="{% static 'images/home-pics/trimed2.jpg' %}"
	{% elif random_num == 7 %} src="{% static 'images/home-pics/trimed3.jpg' %}"
	{% endif %}>

	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<hr>
				<div class="fuchidori">
					<h3><span class="bold">学習院大学 国社生だけのOB・OG相談サイト</h3>
					<h1 class="heading" style="margin-top:1px;">Kiite-me<span class="red">!</span></h1>
					<!-- <a href="#about" class="smoothScroll btn btn-default">このサイトについて ↓</a> -->
				</div>	
			</div>
		</div>
	</div>		
</section>

<!-- about section -->
<section id="about">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<h1 class="heading bold">Kiite-me<span class="red">!</span><br class="br-sp"> って何？</h1>
				<br>
			</div>
			<div class="wow fadeInUp" data-wow-delay="0.9s">
				<div class="aboutline">
					<h3>歴史の浅い学習院大学の国際社会科学部<br><br>国社生らしい就活の仕方がわからない...<br>でも就活の相談ができる先輩もいない...</h3>
					<br>
					<h2>そんな国社の在学生専用の<br>
						「OB・OG就活相談サイト」<br class="br-sp">がここ、Kiite-me<span class="red">!</span>です！</h2>
				</div>
			</div>
			<hr>
		</div>
	</div>
</section>


<section id="howto">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h1 class="heading bold">使い方</h1>
				<h2 class="subheading">ようするに、知恵袋サイトなんです</h2>
				<div class="flexdiv">
					<div class="docspace">
						<p>使い方はカンタン！</p>
						<p>質問系サイトのように、</p>
						<ul>
							<li>質問のタイトル (概要)</li>
							<li>ハッシュタグ</li>
							<li>詳細内容</li>
						</ul>
						<p>の3つを記入して投稿するだけです！</p>
						<br>
						<p>なんでも聞いてみましょう！</p>
						<p style="font-size:12px;color:gray;line-height:18px;">※なお質問は身元の確認がとれた卒業生のみに公開され、他の在学生ユーザーに閲覧されることはありません。</p>
					</div>
					<div class="imgspace">
						<img src="{%static 'images/howto.png' %}" alt="image showing how to use">
					</div>
				</div>
			</div>
		</div>
		<hr>
	</div>
</section>
			
<section id="faq">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<h1 class="heading bold">よくある質問</h1>
				<h2 class="subheading">やっぱり気になりますよね、ソコ</h2>
				<br>
			</div>
			<div class="wow fadeInUp" data-wow-delay="0.9s">
					<div class="cp_actab">
					<input id="tab-one" type="checkbox" name="tabs">
					<label for="tab-one">質問していいのは就活のことだけ？</label>
						<div class="cp_actab-content">
							<p>そんなことはないです！<br>
								就活以外にも授業や留学のことなどなんでもお聞きください。<br>
								質問内容に合わせたハッシュタグを用意しているのでぜひ活用してください！</p>
						</div>
					</div>
					
					<div class="cp_actab">
					<input id="tab-two" type="checkbox" name="tabs">
					<label for="tab-two">お金はかかりますか？</label>
						<div class="cp_actab-content">
							<p>いいえ！<br>
								完全無料なので有料プランも課金システムもないです。<br>
								学生時代に学部事務室のお手伝いをしていた卒業生が中心となって始めたボランティアサービスなので、<br>
								安心してご利用いただけます！</p>
						</div>
					</div>
			
					<div class="cp_actab">
					<input id="tab-three" type="checkbox" name="tabs">
					<label for="tab-three">質問に答える卒業生はどんな人？</label>
						<div class="cp_actab-content">
							<p>国社の1期生と2期生を中心にメーカー、商社、IT、通信、広告業界などなど、<br>
								業界も会社規模も多様なメンバーが卒業生として参加しています！</p>
						</div>
					</div>
			</div>
			<hr>
		</div>
	</div>
</section>


<!-- team section -->
<section id="team">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h1 class="heading bold">OB・OG業界例</h1>
				<h2 class="subheading">他にもメーカーやIT・通信など<br class="br-sp">様々な業界のOB・OGが答えます！</h2>
			</div>
			<div class="col-md-4 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="0.9s">
				<div class="team-wrapper">
					<img src="{% static 'images/yurie1.jpg' %}" class="img-responsive" alt="team img">
					<div class="team-des">
						<h4>マーケティング</h4>
						<h5>2020年度卒業生</h5>
						<h3>佐藤ゆりえ</h3>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="1.3s">
				<div class="team-wrapper">
					<img src="{% static 'images/dougpic.jpg' %}" class="img-responsive" alt="team img">
					<div class="team-des">
						<h4>広告代理店</h4>
						<h5>2019年度卒業生</h5>
						<h3>武内修平</h3>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="1.6s">
				<div class="team-wrapper">
					<img src="{% static 'images/toda1.jpg' %}" class="img-responsive" alt="team img">
					<div class="team-des">
						<h4>エアライン系商社</h4>
						<h5>2019年度卒業生</h5>
						<h3>戸田健太郎</h3>
					</div>
				</div>
			</div>
		</div><hr>
	</div>
</section>


	<div class="container">
		<div class="row">
			<div class="col-md-6 col-sm-6 wow fadeInUp" data-wow-delay="0.8s">
				<img src="{% static 'images/homepic6vert.jpg' %}" class="pcver img-responsive" alt="about img">
			</div>
			<div class="col-md-6 col-sm-6 wow fadeInUp" data-wow-delay="0.9s">
				<h3>Message</h3>
				<p>自分がまだ国社の学生だった頃、学部の後輩向けの就活相談イベントに参加した時によく聞かれた質問の一つが「国社ならではの就活方法ってありますか？」でした。<br>
					これって自分が就活していた時に実際に感じていたことだし、今の在学生だって気になっているところなんだと思います。<br>
					就活を終えて社会人生活をスタートさせた今、自分が国際社会科学部の初めてのOBとして「国社生ならではの就活ができたのか」答えは分からないまま毎日仕事に取り組んでいます。<br>
					新型ウイルスの影響でＯＢ・ＯＧ訪問や先輩に相談をする機会が減ってしまった今こそ、<br>
					自分達が育った学部の後輩のために "何か" がしたくてこのウェブサイトを立ち上げました。
					<br>
					就活のことでも、授業のことでも分からないことがあればなんでも聞いてみてください。
					困ったら何でもキイテミ！<br>気軽に使ってみてください！
					<br>
					<br>
					代表：武内修平（2019年度卒業生）
				</p>
				<img src="{% static 'images/homepic6hori.jpg' %}" class="spver img-responsive" alt="about img">
			</div>
		</div>
	</div>

<!-- contact section -->
<section id="contact">
	<div class="container" style="padding-bottom:20px;">
		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<h2 class="heading bold"><a href="{% url 'signup' %}">登録はコチラ!</a></h2>
				<h2 class="subheading">困ったらなんでもキイテミ！<br class="br-sp">OB・OGが疑問に答えます！
				<br><a href="{% url 'contactForm' %}" style="line-height:38px;">お問い合わせはコチラから</a></h2>
			</div>
		</div>
	</div>
</section>

<!-- copyright section -->
<section id="copyright">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-sm-8 col-xs-9">
				<p>Copyright ©2021 Kiite-me!</p>
			</div>
			<div class="col-md-4 col-sm-4 col-xs-3">
				<a href="#home" class="smoothScroll">▲</a>
			</div>
		</div>
	</div>
</section>
{% if not user.is_authenticated %}
<div class="spver signup-btn">
	<a href="{% url 'signup' %}">
		<button type="button" class="btn btn-default btn-lg" style="box-shadow: 1px 1.5px 3px 1px rgb(0 0 255 / 20%); color:#fff; background-color:#51d095;">Sign up here!</button>
	</a>
</div>
{% endif %}
{% endblock %}

templates/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="main users-new">
    <div class="container">
      <div class="form-heading">Log in</div>
      <div class="form users-form">
        <div class="form-body">
          <form method="POST" action="">
            {% csrf_token %}
            <p>メールアドレス</p>
            <input class="form-control" name="email" value="123@gmail.com" autofocus="">
            <hr>
            <p>パスワード 　※入力済です、そのままログインを押下してください</p>
            <input class="form-control" type="password" name="password" value="shuheitakeuchi">
            <hr>
            <input type="submit" value="ログイン">
          </form>       
          <a href="{% url 'reset_password' %}">パスワードをお忘れですか？</a>
          <p>アカウント作成は<a href="{% url 'signup' %}">コチラ</a></p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/signup.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="main users-new">
    <div class="container">
      <div class="form-heading">Sign up</div>
      <div class="form users-form">
        <div class="form-body">
          <p>
            <span style="margin-right: 4px; padding-top: 4px; color:#931919;">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
              </svg>
            </span>
            学習院大学の在学生および卒業生でない方の利用はご遠慮ください。
          </p>
  
          <form method="POST" action="">
            {% csrf_token %}
            <hr>
              <p>ご本人様のお名前</p>
              {{ form.real_name | add_class:"form-control" | attr:"autofocus" }}
              <hr>
              
              <p>メールアドレス</p>
              {{ form.email | add_class:"form-control" }}
              <p>　※各種キャリアメールアドレスやicloud.comのドメインは使用不可な場合があります。gmailなどフリーメールアドレスのご利用を推奨します。</p>
              <hr>
              
              <p>ユーザーネーム</p>
              {{ form.name | add_class:"form-control" }}
              <hr>

              <p>パスワード</p>
              {{ form.password1 | add_class:"form-control" }}
              <hr>

              <p>パスワード（確認用）</p>
              {{ form.password2 | add_class:"form-control" }}
              <hr>

              <p>入学年度（西暦）</p>
              {{ form.entry_year | add_class:"form-control" }}
              <hr>

              <p>在籍状況</p>
              {{ form.student_status | add_class:"form-control" }}
              <hr>

              <div id="signup_alumni_form" class="hide">  
                <div class="job_form">
                  <p>業界</p>
                  <p class="fs-13" style="margin:0;">大分類</p>
                  {{ form.job_parent_category | add_class:"form-control parent-form" }}
                  <br>
                  <p class="fs-13" style="margin:0;">小分類</p>
                  {{ form.job_category | add_class:"form-control" | attr:"disabled" }}
                  <hr>
                </div>

                <p>職種</p>
                {{ form.job_type | add_class:"form-control" }}
                <hr>
  
                <p>内定を獲得していた業界</p>
                {{ formset.management_form }}
                {% for line_form in formset %}
                  <div class="job_form">
                    {% for hidden in line_form.hidden_fields %} <!-- necessary for some reason... -->
                      {{ hidden }}
                    {% endfor %}
                    <button type="button" class="btn btn-danger job-form-reset-btn hide">リセット</button>
                    <p>{{ forloop.counter }}</p>
                    <p class="fs-13" style="margin:0;">大分類</p>
                    {{ line_form.offered_job_parent_category | add_class:"form-control parent-form" }}
                    <br>
                    <p class="fs-13" style="margin:0;">小分類</p>
                    {{ line_form.offered_job_child_category | add_class:"form-control child-form" | attr:"disabled" }}
                    <div class="emptybox"></div>
                    {{ line_form.DELETE | add_class:"hide" }}
                  </div>
                {% endfor %}
                <hr>
              </div>

              {{ form.errors }}
              <p>※ 卒業生として登録される際には、運営によって身元の確認が行われます。その間はサービスをご利用できませんのでご了承ください。</p>
              <p>※ 登録することで、<a href="{% url 'terms_of_use' %}" target="_blank" rel="noopener noreferrer">利用規約</a>と<a href="{% url 'privacy_policy' %}" target="_blank" rel="noopener noreferrer">プライバシーポリシー</a>に同意したものとみなされます。</p>

            <input type="submit"  id="submit" name="Create User" value="登録">
          </form>
          <p>すでにアカウントをお持ちの方は<a href="{% url 'login'%}">コチラ</a></p>
        </div>
      </div>
    </div>
  </div>

<script>
  // 業界選択時の処理
  const categories = {
    {% for parent in parent_category_list %}
      '{{ parent.pk }}' : [
        {% for category in parent.alumnijobchildcategory_set.all %}
          {
            'pk': '{{ category.pk }}',
            'name': '{{ category.name }}'
          },
        {% endfor %}
      ],
    {% endfor %}
  };

  $('.job_form select.parent-form').on('change', function () {
    const childJobCategoryElem = $(this).siblings('select');
    const parentJobCategoryElem = $(this);

    childJobCategoryElem.children().remove();
    childJobCategoryElem.removeAttr('disabled');
    $(this).siblings('.job-form-reset-btn').removeClass('hide');

    const parentId = parentJobCategoryElem.val();
    const categoryList = categories[parentId];

    // 子カテゴリの選択肢を作成、追加。
    childJobCategoryElem.append($('<option value="">---------</option>'));
    for (const category of categoryList) {
      const option = $('<option>');
      option.val(category['pk']);
      option.text(category['name']);
      childJobCategoryElem.append(option);
    }
  });

  // reset job select form
  $(document).on('click', '.job-form-reset-btn', function() {
    $(this).siblings('input[type="checkbox"]').prop('checked', true);
    $(this).siblings('select.parent-form').find('option:eq(0)').prop('selected', true);
    $(this).siblings('select.child-form').prop('disabled', true);
    $(this).siblings('select.child-form').children('option:not(option:eq(0))').remove();
    $(this).addClass('hide');
  });

  $(document).on('change', 'select.child-form', function() {
    $(this).siblings('input[type="checkbox"]').prop('checked', false);
  });

  $('#id_student_status').on('change', function () {
    if ($(this).val() == '卒業生') {
      $('#signup_alumni_form').removeClass('hide');
    } else {
      if (!$('#signup_alumni_form').hasClass('hide')) {
        $('#signup_alumni_form').addClass('hide');
      }
    }
  });


  // form validation
  $('input[type="submit"]').on('click', function () {
    for (i=0; i<3; i++) {
      const thisRowChildForm = $('select.child-form:eq(' + i + ')');
      if(typeof thisRowChildForm.attr('disabled') === 'undefined' || thisRowChildForm.attr('disabled') === false) {
        if(thisRowChildForm.val() == '') {
          alert('内定を獲得していた業界の' + (i+1) + '列目の子分類が未選択です。');
          return false;
        }
      }
    }
    if (typeof $('#id_job_category').attr('disabled') === 'undefined' || $('#id_job_category').attr('disabled') === false) {
      if ($('#id_job_category').val() == '') {
        alert('現在の業界の子分類が未選択です。');
        return false;
      }
    }
  });

</script>
{% endblock %}